Prep Javascript Functions First Draft Nelson Daza
neldaza/prep-90921-code-solutions pull request #13
Opened 2021-09-22 21:45 UTC by neldaza

<img width="1440" alt="Screen Shot 2021-09-22 at 5 44 55 PM" src="https://user-images.githubusercontent.com/88061673/134426302-4d2593ef-ad95-49df-b741-7037ba7ffdd9.png">

2021-09-23 18:29 UTC, scbowler requested changes
Looking good, but 1 update needed. Let me know if you have any questions.

2021-09-23 18:29 UTC, scbowler commented on prep-javascript-functions/main.js
> +  return firstName + lastName;
Here you want a space between the first and last name

2021-09-23 18:29 UTC, scbowler commented on prep-javascript-functions/main.js
> +var name = getFullName('Nelson ', 'Daza');
Adding a space at the end of the first name isn't ideal. People using your function wouldn't know to do that or remember to do that. The space should be added by the function as mentioned above

2021-09-23 22:35 UTC, neldaza commented
updated!

<img width="1440" alt="Screen Shot 2021-09-23 at 6 35 00 PM" src="https://user-images.githubusercontent.com/88061673/134592829-7098478d-bf13-480a-9650-338d2e68095e.png">

2021-09-24 01:25 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍 

1 FYI comment, no changes required

2021-09-24 01:25 UTC, scbowler commented on prep-javascript-functions/main.js
> +var Greeting = getGreeting('Nelson');
We want to always start variable and function names with lowercase letter.

2021-09-24 03:24 UTC, merged