Prep Javascript Dom Creation First Draft W.I.P Nelson Daza
neldaza/prep-90921-code-solutions pull request #18
Opened 2021-09-25 19:55 UTC by neldaza

squashed out every other step, got stuck on final question, any tips?
<img width="1440" alt="Screen Shot 2021-09-25 at 3 53 56 PM" src="https://user-images.githubusercontent.com/88061673/134784534-d5597c10-f2f1-417c-95f1-e48f597ab9b6.png">
s?

2021-09-25 21:17 UTC, scbowler requested changes
A couple updates needed. Let me know if you have any questions.

2021-09-25 21:17 UTC, scbowler commented on prep-javascript-dom-creation/index.html
> +    var $container = document.querySelector('div.container');
Here the selector should be `#container` or `div#container`

2021-09-25 21:17 UTC, scbowler commented on prep-javascript-dom-creation/index.html
> +    $heading.appendChild($container);
Here you want to append `$heading` into `$container` so it should be the other way around compared to your code. `$container.appendChild($heading);`.

2021-09-27 23:29 UTC, neldaza commented
updated! thanks Scott!
<img width="1440" alt="Screen Shot 2021-09-27 at 7 28 55 PM" src="https://user-images.githubusercontent.com/88061673/134998723-0d5bdf95-9db5-463a-aa81-b1d67893b3ad.png">
<img width="1440" alt="Screen Shot 2021-09-27 at 7 27 30 PM" src="https://user-images.githubusercontent.com/88061673/134998725-2f517e7e-c33a-4765-b395-352772fbe21e.png">

2021-09-28 22:27 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2021-09-29 10:09 UTC, merged